### ISSUE TITLE
Comportement particules d'impact

### ISSUE THREAD

**Issue by Fayveline** [Falquano/Proto-Coop-Plateformer#7]
Actuellement les particules sont instanciées quand un joueur atteri sur ses petons ou saute. Il ne faut pas de particule quand il saute.

De plus, je propose un changement de comportement : pour avoir des particules avec les wall grab, et quand on projete un joueur sur un mur (ce qui va devenir important bientôt !), on pourrait instancier les particules sur n'importe quel impact si il se fait avec une vitesse supérieur à un threshold.

Merci d'avoir écouté mon TED talk.

**Comment by SebPautot** [comment]
Issue fixed with 4bfd33d980ea1aa58fe11726634f8c9770add015

Jumping was setting IsGrounded to false before the player left the ground, the next frame was then setting it to false again because it didn't leave the ground, but then it was set to false again because the player left the ground because of the actual jump.
